.idea/Fakezone_A15.iml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, Fakezon/src/main/java/DomainLayer/Model/Basket.java, Fakezon/src/main/java/DomainLayer/Model/Cart.java, Fakezon/src/main/java/DomainLayer/Model/Guest.java, Fakezon/src/main/java/DomainLayer/Model/Registered.java, Fakezon/src/main/java/DomainLayer/Model/User.java, Fakezon/src/main/java/DomainLayer/Model/UserType.java
Implement cart and basket #51
Implement Guest and Registered states for User #55
=> finish issue #55 and issue #51

Fakezon/src/main/java/DomainLayer/Interfaces/IRegisteredRole.java, Fakezon/src/main/java/DomainLayer/Interfaces/IUserType.java, Fakezon/src/main/java/DomainLayer/Model/Registered.java, Fakezon/src/main/java/DomainLayer/Model/RegisteredRole.java, Fakezon/src/main/java/DomainLayer/Model/StoreFounder.java, Fakezon/src/main/java/DomainLayer/Model/StoreManager.java, Fakezon/src/main/java/DomainLayer/Model/StoreOwner.java, Fakezon/src/main/java/DomainLayer/Model/SystemAdministrator.java, Fakezon/src/main/java/DomainLayer/Model/UnassignedRole.java, Fakezon/src/main/java/DomainLayer/Model/UserType.java
=> finish issue #54

Fakezon/src/main/java/DomainLayer/Interfaces/IAuthenticator.java, Fakezon/src/main/java/DomainLayer/Interfaces/IDelivery.java, Fakezon/src/main/java/DomainLayer/Interfaces/IPayment.java
Introduce IAuthenticator for user authentication, enhance IDelivery with a delivery method, and expand IPayment to include payment and refund methods.
=> resolves #56: add interfaces idelivery ipayment iauthenticator

Fakezon/src/main/java/DomainLayer/Model/ProductRating.java, Fakezon/src/main/java/DomainLayer/Model/Store.java, Fakezon/src/main/java/DomainLayer/Model/StoreProduct.java, Fakezon/src/main/java/DomainLayer/Model/StoreRating.java
updated rating in StoreRating and ProductRating
=> rating store and product

Fakezon/pom.xml, logback.xml
run 'mvn clean install' to install the dependency
=> Add logback dependencies

Fakezon/.gitignore
=> added unwanted folders to .gitignore

Fakezon/src/main/java/ApplicationLayer/Interfaces/IStoreService.java, Fakezon/src/main/java/ApplicationLayer/Services/StoreService.java, Fakezon/src/main/java/ApplicationLayer/Services/SystemService.java, Fakezon/src/main/java/DomainLayer/Model/Store.java, Fakezon/src/test/java/AcceptanceTesting/StoreServiceAcceptanceTest.java, Fakezon/src/test/java/UnitTesting/StoreTest.java
will create a new issue for unit tests
=> 144 use case 411 request administrators permissions   storeservice layer

.vscode/settings.json, Fakezon/src/main/java/ApplicationLayer/Services/UserService.java, Fakezon/src/main/java/DomainLayer/IRepository/IUserRepository.java, Fakezon/src/main/java/DomainLayer/Interfaces/IUserType.java, Fakezon/src/main/java/DomainLayer/Model/Guest.java, Fakezon/src/main/java/DomainLayer/Model/Registered.java, Fakezon/src/main/java/DomainLayer/Model/User.java, Fakezon/src/main/java/DomainLayer/Model/UserType.java, Fakezon/src/main/java/InfrastructureLayer/Repositories/UserRepository.java, Fakezon/src/test/java/UnitTesting/RegisteredTest.java
in userService:
- add: login()
in user:
- add: getPassword(), and update accordingly.
in userRepository
- add: addUser()
- delete: saveUser()
=> update userRepository and userService

Fakezon/src/main/java/ApplicationLayer/Interfaces/ISystemService.java, Fakezon/src/main/java/ApplicationLayer/Services/SystemService.java, Fakezon/src/test/java/AcceptanceTesting/SystemServiceAcceptanceTest.java
We will fix test: UserRegistration_InvalidEmail_Failure when we write all tests
=> update systemService to return response

Fakezon/src/main/java/DomainLayer/IRepository/IStoreRepository.java, Fakezon/src/main/java/DomainLayer/Model/Store.java, Fakezon/src/main/java/InfrastructureLayer/Repositories/StoreRepository.java, Fakezon/src/test/java/UnitTesting/StoreRepositoryTest.java
create a function to get 10 highest stores and StoreRepositoryTest
=> 263 create a function to get 10 highest stores

Fakezon/src/main/java/InfrastructureLayer/Security/TokenService.java, Fakezon/src/main/resources/application.properties
Refactor TokenService to initialize signing key from Base64 encoded secret and update application.properties to include jwt.secret
=> add jwt secret to application properties

Fakezon/src/main/java/ApplicationLayer/DTO/StoreProductDTO.java, Fakezon/src/main/java/ApplicationLayer/Interfaces/IStoreService.java, Fakezon/src/main/java/ApplicationLayer/Interfaces/ISystemService.java, Fakezon/src/main/java/ApplicationLayer/Services/StoreService.java, Fakezon/src/main/java/ApplicationLayer/Services/SystemService.java, Fakezon/src/main/java/DomainLayer/Model/Store.java, Fakezon/src/main/java/DomainLayer/Model/StoreProduct.java, Fakezon/src/main/java/com/fakezone/fakezone/controller/StoreController.java, Fakezon/src/test/java/UnitTesting/StoreServiceTest.java
deleted - addStoreAuctionProductDays
=> add storeId to storeProduct &

Fakezon/src/main/java/ApplicationLayer/DTO/BasketDTO.java, Fakezon/src/main/java/ApplicationLayer/DTO/StoreDTO.java, Fakezon/src/main/java/ApplicationLayer/DTO/StoreProductDTO.java, Fakezon/src/main/java/ApplicationLayer/Interfaces/IOrderService.java, Fakezon/src/main/java/ApplicationLayer/Interfaces/IStoreService.java, Fakezon/src/main/java/ApplicationLayer/Interfaces/ISystemService.java, Fakezon/src/main/java/ApplicationLayer/Interfaces/IUserService.java, Fakezon/src/main/java/ApplicationLayer/Services/OrderService.java, Fakezon/src/main/java/ApplicationLayer/Services/StoreService.java, Fakezon/src/main/java/ApplicationLayer/Services/SystemService.java, Fakezon/src/main/java/ApplicationLayer/Services/UserService.java, Fakezon/src/main/java/DomainLayer/Interfaces/IOrder.java, Fakezon/src/main/java/DomainLayer/Interfaces/IOrderRepository.java, Fakezon/src/main/java/DomainLayer/Interfaces/IStore.java, Fakezon/src/main/java/DomainLayer/Model/Basket.java, Fakezon/src/main/java/DomainLayer/Model/Cart.java, Fakezon/src/main/java/DomainLayer/Model/Order.java, Fakezon/src/main/java/DomainLayer/Model/OrderedProduct.java, Fakezon/src/main/java/DomainLayer/Model/Registered.java, Fakezon/src/main/java/DomainLayer/Model/Store.java, Fakezon/src/main/java/DomainLayer/Model/User.java, Fakezon/src/main/java/InfrastructureLayer/Repositories/OrderRepository.java, Fakezon/src/main/java/com/fakezone/fakezone/controller/OrderController.java, Fakezon/src/main/java/com/fakezone/fakezone/controller/UserController.java, Fakezon/src/test/java/AcceptanceTesting/NewSystemServiceAcceptanceTest.java, Fakezon/src/test/java/UnitTesting/OrderRepositoryTest.java, Fakezon/src/test/java/UnitTesting/OrderServiceTest.java, Fakezon/src/test/java/UnitTesting/OrderTest.java, Fakezon/src/test/java/UnitTesting/UserControllerTest.java, Fakezon/src/test/java/UnitTesting/UserTest.java
changed view cart, purchases and classes backet, order, cart, added orderdProduct
=> 326 change basket and view cart 265   domain

Fakezon/src/test/java/NewAcceptanceTesting/AT_User/AT_Registered/Open_Store.java, Fakezon/src/test/java/NewAcceptanceTesting/AT_User/AT_StoreOwner/StoreOwner_Add_product.java
there are no tests in addProductToStore (SystemService) for the next:
-invalid storeId (no store exist)
-invalid userId (user is not StoreOwner)
-invalid productName (empty or null)
-invalid productDescription (empty or null)
I wrote all the tests, and they are in comments.
=> finish AT Use-case: 4.1 StoreOwner - Add a product

Fakezon/src/test/java/NewAcceptanceTesting/AT_User/AT_Guest/Save_Products_in_Purchase_Basket.java, Fakezon/src/test/java/NewAcceptanceTesting/TestHelper.java
the addToBasket function (in systemservice) is working just for registered users.
I think we will need to fix this in the future, but for now, it works great for registered :)
maby open an issue to fix addToBasket function, and an issue to update this ac.
=> finish at Use-case: 2.3 Save Products in Purchase Basket

Fakezon/pom.xml, Fakezon/src/main/java/ApplicationLayer/Interfaces/ISystemService.java, Fakezon/src/main/java/ApplicationLayer/Services/SystemService.java, Fakezon/src/main/java/com/fakezone/fakezone/controller/OrderController.java, Fakezon/src/main/java/com/fakezone/fakezone/controller/ProductController.java, Fakezon/src/main/java/com/fakezone/fakezone/controller/StoreController.java, Fakezon/src/test/java/AcceptanceTesting/SystemServiceAcceptanceTest.java, Fakezon/src/test/java/NewAcceptanceTesting/AT_User/AT_Guest/Guest_User_Access_to_Product_Information.java, Fakezon/src/test/java/NewAcceptanceTesting/AT_User/AT_Guest/Guest_User_Access_to_Store.java, Fakezon/src/test/java/NewAcceptanceTesting/AT_User/AT_Guest/Product_Search.java, Fakezon/src/test/java/UnitTesting/OrderControllerTest.java, Fakezon/src/test/java/UnitTesting/ProductControllerTest.java, Fakezon/src/test/java/UnitTesting/StoreControllerTest.java
I changed some of the controllers where it was needed
=> 340 remove token varification from systemservice

Fakezon/src/main/java/ApplicationLayer/Interfaces/IStoreService.java, Fakezon/src/main/java/ApplicationLayer/Interfaces/IUserService.java, Fakezon/src/main/java/ApplicationLayer/Services/StoreService.java, Fakezon/src/main/java/ApplicationLayer/Services/SystemService.java, Fakezon/src/main/java/ApplicationLayer/Services/UserService.java, Fakezon/src/main/java/DomainLayer/Interfaces/IStore.java, Fakezon/src/main/java/DomainLayer/Model/Store.java, Fakezon/src/main/java/DomainLayer/Model/StoreProduct.java, Fakezon/src/test/java/UnitTesting/StoreServiceTest.java, Fakezon/src/test/java/UnitTesting/StoreTest.java
added returnProductsToStores if purchase failed
added decrementProductsInStores
added clearUserCart if purchase Succeed
=> remove sync

Fakezon/src/main/java/ApplicationLayer/Interfaces/IStoreService.java, Fakezon/src/main/java/ApplicationLayer/Interfaces/ISystemService.java, Fakezon/src/main/java/ApplicationLayer/Services/StoreService.java, Fakezon/src/main/java/ApplicationLayer/Services/SystemService.java, Fakezon/src/main/java/DomainLayer/Interfaces/IStore.java, Fakezon/src/main/java/DomainLayer/Model/AuctionProduct.java, Fakezon/src/main/java/DomainLayer/Model/Registered.java, Fakezon/src/main/java/DomainLayer/Model/Store.java, Fakezon/src/main/java/DomainLayer/Model/helpers/AuctionEvents/AuctionGotHigherBidEvent.java, Fakezon/src/main/java/com/fakezone/fakezone/controller/StoreController.java, Fakezon/src/test/java/UnitTesting/AuctionProductTest.java, Fakezon/src/test/java/UnitTesting/StoreControllerTest.java, Fakezon/src/test/java/UnitTesting/StoreTest.java
and added the decline event in case of someone bid higher then me
changed daysToEnd to Minuets
=> changed daysToEnd to Minuets

Fakezon/src/main/java/DomainLayer/Model/Store.java, Fakezon/src/test/java/NewAcceptanceTesting/AT_User/AT_StoreOwner/StoreOwner_Owner_Appointment.java
=> added StoreOwner_Owner_Appointment AT

Fakezon/src/main/java/ApplicationLayer/Interfaces/ISystemService.java, Fakezon/src/main/java/ApplicationLayer/Interfaces/IUserService.java, Fakezon/src/main/java/ApplicationLayer/Services/SystemService.java, Fakezon/src/main/java/ApplicationLayer/Services/UserService.java, Fakezon/src/main/java/DomainLayer/IRepository/IUserRepository.java, Fakezon/src/main/java/InfrastructureLayer/Repositories/UserRepository.java, Fakezon/src/test/java/UnitTesting/SystemServiceAdminTest.java, Fakezon/src/test/java/UnitTesting/UserRepositoryTest.java, Fakezon/src/test/java/UnitTesting/UserServiceAdminTest.java
nobody called the addUnsignedUser function so i renamed it and updated it to give a negative ID
the remove function was already written, I just added tests to it
=> create and delete unsigned user

Fakezon/src/test/java/NewAcceptanceTesting/AT_User/AT_StoreOwner/StoreOwner_change_permissions.java, Fakezon/src/test/java/NewAcceptanceTesting/TestHelper.java
added to test helper register_and_login4 and register_and_login5
and StoreOwner_change_permissions with Concurrency check
=> AT 4.7 with Parallel test

Fakezon/src/main/java/ApplicationLayer/Interfaces/IOrderService.java, Fakezon/src/main/java/ApplicationLayer/Interfaces/ISystemService.java, Fakezon/src/main/java/ApplicationLayer/Interfaces/IUserService.java, Fakezon/src/main/java/ApplicationLayer/Services/OrderService.java, Fakezon/src/main/java/ApplicationLayer/Services/SystemService.java, Fakezon/src/main/java/ApplicationLayer/Services/UserService.java, Fakezon/src/main/java/DomainLayer/Interfaces/IOrderRepository.java, Fakezon/src/main/java/DomainLayer/Model/Registered.java, Fakezon/src/main/java/InfrastructureLayer/Repositories/OrderRepository.java, Fakezon/src/main/java/com/fakezone/fakezone/controller/OrderController.java, Fakezon/src/main/java/com/fakezone/fakezone/controller/UserController.java, Fakezon/src/test/java/NewAcceptanceTesting/AT_User/AT_Registered/OrderRetrievalIntegrationTest.java, Fakezon/src/test/java/UnitTesting/OrderControllerTest.java, Fakezon/src/test/java/UnitTesting/OrderRepositoryTest.java, Fakezon/src/test/java/UnitTesting/OrderServiceTest.java, Fakezon/src/test/java/UnitTesting/RegisteredTest.java, Fakezon/src/test/java/UnitTesting/SystemServiceTest.java, Fakezon/src/test/java/UnitTesting/UserControllerTest.java, Fakezon/src/test/java/UnitTesting/UserServiceTest.java
Removed old getOrderByUser in User service and registered
added AT and UT 
changed controllers
=> 448 add systemservice method getalluserorders

Fakezon/src/main/java/ApplicationLayer/Interfaces/IStoreService.java, Fakezon/src/main/java/ApplicationLayer/Interfaces/ISystemService.java, Fakezon/src/main/java/ApplicationLayer/Services/StoreService.java, Fakezon/src/main/java/ApplicationLayer/Services/SystemService.java, Fakezon/src/main/java/DomainLayer/Interfaces/IStore.java, Fakezon/src/main/java/DomainLayer/Model/Store.java, Fakezon/src/main/java/InfrastructureLayer/Repositories/UserRepository.java, Fakezon/src/main/java/com/fakezone/fakezone/controller/StoreController.java, Fakezon/src/test/java/NewAcceptanceTesting/AT_User/AT_Registered/Closing_Store.java, Fakezon/src/test/java/UnitTesting/UserRepositoryTest.java
POST /api/store/closeStoreByAdmin/{storeId}/{adminId}
=> Close store by admin
